### ISSUE TITLE
How to use onSubmitEditing and this.refs from react native in Reput

### ISSUE THREAD

**Issue by rasanu** [sospedra/reinput#12]
How to use onSubmitEditing and this.refs from react native in Reput

**Comment by sospedra** [comment]
For the `onSubmitEditing` you just need to send it as a prop since we support all the `TextInput` props by default.

To hook any ref we expose the `register` prop so you can easily reach the `TextInput` component containing the React hooks and content.

**Comment by khanisak** [comment]
Hi Sospedra, 

Does reinput support TextInput `style` props?  
Something like this <Reinput style={mystyle} />

Because I want to set `MarginLeft` but it didn't work. 
But if I use `marginLeft` props, it works.
thanks

**Comment by sospedra** [comment]
It does support all the react-native TextInput props.
As you mentioned `MarginLeft` (capitalized) doesn't work since it's not a valid style.
