### ISSUE TITLE
Error messages are not shown completely

### ISSUE THREAD

**Issue by chmartinez** [sospedra/reinput#25]
The assertive error messages are not handling errors properly. If you have an error with two or more lines of text, the all component looks funny:

<img width="484" alt="screen shot 2018-09-21 at 09 24 09" src="https://user-images.githubusercontent.com/2874963/45866245-70290480-bd80-11e8-9883-14b853e66f77.png">

**Comment by chmartinez** [comment]
Check this out:

![reinput-fixed](https://user-images.githubusercontent.com/2874963/60836877-053da280-a1c7-11e9-9d27-c12e512536c7.gif)

I think we can close this one. What do you think:?

**Comment by sospedra** [comment]
ty for the report
