### ISSUE TITLE
Text is transparent when passing the value using the component state...

### ISSUE THREAD

**Issue by cuauhtlahuac** [sospedra/reinput#42]
The text of input don't shows color, navigating trough the code, the team detect a _transparent_ style in the text. We think that the issue happen when the component don't detect correctly the first time the value, then never change the style and it maintains the transparency. We like the component and we hope that you can fix this issue.

Thank you.

**Comment by sospedra** [comment]
Can you share a reproducible example?

**Comment by chrisbasso** [comment]
The same thing happens to me, but only on iOS, when I add secureTextEntry. When the value is set by "state" the text is transparent

**Comment by chrisbasso** [comment]
I just found the error, in "Input / styles.js"

line 54
color: hasValue? styles.color: 'transparent',

**Comment by sospedra** [comment]
fixed in #47
